Repository jenkins-x-charts/vault-instance, pull requests merged in 2021-01, with the labels that each got.

#3 fix: improve chart customizability
  charts/vault-instance/templates/cr.yaml
  charts/vault-instance/values.yaml
Labels: lgtm, ok-to-test, size/S

#4 fix: set version for bankVaults, and upgrade Vault
  charts/vault-instance/values.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#5 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/M, updatebot
